/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CustomerSidebar: typeof import('./src/components/customer/CustomerSidebar.vue')['default']
    CustomerTopbar: typeof import('./src/components/customer/CustomerTopbar.vue')['default']
    DeliverySidebar: typeof import('./src/components/delivery/DeliverySidebar.vue')['default']
    DeliveryTopbar: typeof import('./src/components/delivery/DeliveryTopbar.vue')['default']
    GoogleMapView: typeof import('./src/components/map/GoogleMapView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuperAdminSidebar: typeof import('./src/components/superadmin/SuperAdminSidebar.vue')['default']
    SuperAdminTopbar: typeof import('./src/components/superadmin/SuperAdminTopbar.vue')['default']
  }
}
