/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/customer/CustomerDashboard': RouteRecordInfo<'/customer/CustomerDashboard', '/customer/CustomerDashboard', Record<never, never>, Record<never, never>>,
    '/customer/CustomerTrackMap': RouteRecordInfo<'/customer/CustomerTrackMap', '/customer/CustomerTrackMap', Record<never, never>, Record<never, never>>,
    '/delivery/DeliveryDashboard': RouteRecordInfo<'/delivery/DeliveryDashboard', '/delivery/DeliveryDashboard', Record<never, never>, Record<never, never>>,
    '/delivery/DeliveryTrackMap': RouteRecordInfo<'/delivery/DeliveryTrackMap', '/delivery/DeliveryTrackMap', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/superadmin/SuperAdminDashBoard': RouteRecordInfo<'/superadmin/SuperAdminDashBoard', '/superadmin/SuperAdminDashBoard', Record<never, never>, Record<never, never>>,
    '/superadmin/SuperAdminManageCustomer': RouteRecordInfo<'/superadmin/SuperAdminManageCustomer', '/superadmin/SuperAdminManageCustomer', Record<never, never>, Record<never, never>>,
    '/superadmin/SuperAdminManageStaff': RouteRecordInfo<'/superadmin/SuperAdminManageStaff', '/superadmin/SuperAdminManageStaff', Record<never, never>, Record<never, never>>,
    '/superadmin/SuperAdminTrackMap': RouteRecordInfo<'/superadmin/SuperAdminTrackMap', '/superadmin/SuperAdminTrackMap', Record<never, never>, Record<never, never>>,
  }
}
